### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by scheibling** [scheiblingco/code-cmd-repeat#1]
- [x] Add customization for terminal command (!!, up&enter, Invoke-History or custom)
- [x] Clear typed text in terminal before running command
- [ ] Extend logging w/ reason for failures
- [x] Fix workflow issues for autopublish

**Comment by matschaffer-roblox** [comment]
That first option would be nice. When switching from https://marketplace.visualstudio.com/items?itemName=Cameron.rerun-last-command I ran into a little confusion due to having `histverify` set in my ZSH. 

I had to turn that off for `!!` to work without an additional enter.

I did `unsetopt histverify` as a workaround for the moment. This _might_ be the default for zsh now. I'm using `zsh4humans` but I don't see it being set there.

Thanks for picking up the development on this. It's a very important part of my usual workflow.

**Comment by scheibling** [comment]
No problem, give me a couple of hours!

**Comment by scheibling** [comment]
> That first option would be nice. When switching from https://marketplace.visualstudio.com/items?itemName=Cameron.rerun-last-command I ran into a little confusion due to having `histverify` set in my ZSH.
> 
> I had to turn that off for `!!` to work without an additional enter.
> 
> I did `unsetopt histverify` as a workaround for the moment. This _might_ be the default for zsh now. I'm using `zsh4humans` but I don't see it being set there.
> 
> Thanks for picking up the development on this. It's a very important part of my usual workflow.

@matschaffer-roblox This is resolved in 0.1.15, should be up on VS Marketplace and OpenVSX in a couple of minutes!

Edit: Will be 0.2.0 soon, should probably bump a minor version for this

**Comment by matschaffer-roblox** [comment]
With this setting I was able to remove the `unsetopt histverify` I'd added to my env and have it this extension work the same as its predecessor.

```
"code-cmd-repeat.repetitionCommand": "!! [enter]"
```

Great work @scheibling - thanks for the quick response 🧡
